name: 财富岛

on:
    workflow_dispatch:
    schedule:
        - cron: "30 * * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jx_cfd

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【财富岛】"
              run: |
                  node onlyOneExecute.js
